### ISSUE TITLE
Consider using ``pre-commit`` hooks for linting

### ISSUE THREAD

**Issue by jrbourbeau** [nsidc/earthaccess#282]
Sometimes it's easy to forget to lint code (I do this all the time!) and then CI builds fail because, for example, `black` isn't happy. We might consider using `pre-commit` hooks here to handle code formatting / linting. That way things like `mypy`, `black`, etc. all run automatically when a developer runs `git commit ...`

@betolink @MattF-NSIDC thoughts? 

### TODO

- [x] Remove `.scripts/lint.sh` and references to it
- [x] Add Ruff (or Flake8) hook to `.pre-commit-config.yaml` (add Ruff config to pyproject.toml)
- [x] Enable pre-commit.ci (I may do this independently)
- [x] Move isort config from script into a file (pyproject.toml; or migrate to Ruff) _Note: now using ruff and config is in `pyproject.toml`_
- [x] Move Black config from script to file _Note: now using ruff and config is in `pyproject.toml`_
- [x] Move Mypy config from script to file. _Note: now in `pyproject.toml`_
- [x] Should we run Mypy with pre-commit? It can be slow (probably not yet on this project?), and pre-commit is meant to not slow you down. _Resolution: No, it'ss run as part of our unit tests now._
- [x] ~~More pre-commit hooks?~~ Lets open specific issues/PRs if we want them.
- [x] Make sure `pre-commit` is a dev dependency (if it isn't already -- haven't checked) 
- [x] Update `CONTRIBUTING.md` to include `pre-commit install`

**Comment by MattF-NSIDC** [comment]
1000 times yes. Pre-commit gets my tools out of my way and I'm never going back :heart_eyes:  Not everyone will use it, so I think we should keep the CI checks... and maybe run them in pre-commit.ci?

**Comment by mfisher87** [comment]
I think we should go forward with this. While we're there, I'd like to remove Flake8 and isort to replace with Ruff. Ruff also has a Black-compatible formatter that I haven't tried yet, so I would probably still leave Black in place for now?

I think we need to:

- [ ] Remove `.scripts/lint.sh` and references to it
- [ ] Enable pre-commit.ci (I may do this independently)
- [ ] Move isort config from script into a file (pyproject.toml; or migrate to Ruff)
- [ ] Move Black config from script to file
- [ ] Move Mypy config from script to file
- [ ] ??

**Comment by jrbourbeau** [comment]
- [ ] Make sure `pre-commit` is a dev dependency (if it isn't already -- haven't checked) 
- [ ] Update `CONTRIBUTING.md` to include `pre-commit install`

**Comment by MattF-NSIDC** [comment]
Good ones! I'll merge all the checklist items into the OP now.

**Comment by mfisher87** [comment]
>Should we run Mypy with pre-commit? It can be slow (probably not yet on this project?), and pre-commit is meant to not slow you down.

Another concern with Mypy is its interface doesn't really work well with pre-commit. Mypy doesn't want to receive a list of changed files to check, it will not do a holistic analysis in this case, so it may pass when a change breaks type correctness.

We can configure it to [_not_ pass filenames](https://pre-commit.com/#hooks-pass_filenames), and then Mypy will run on the whole project, which will be slower. Maybe we should run Mypy as a separate CI step.

**Comment by jhkennedy** [comment]
I updated the check-list here with what's complete, and now everything is checked, so I'm closing this issue as done. :tada:
