### ISSUE TITLE
Populate user guide "explanation"/"discussion"/"concept" pages

### ISSUE THREAD

**Issue by mfisher87** [nsidc/earthaccess#550]
The user guide is for explaining the authentication, search, and access concepts in earthaccess, but they're currently a work in progress
```[tasklist]
### Tasks
- [ ] Populate user-guide/authentication
- [ ] https://github.com/nsidc/earthaccess/issues/855
- [ ] https://github.com/nsidc/earthaccess/issues/854
```

**Comment by andypbarrett** [comment]
Closing as tasks have been converted to separate issues
