### ISSUE TITLE
Add Python (and other core dependency) support policy to our docs

### ISSUE THREAD

**Issue by mfisher87** [nsidc/earthaccess#573]
IMO we should follow the Numpy policy and see how that works for us.

Follow up from discussion in #571 

```[tasklist]
### Tasks
- [x] Adopt a policy by consensus. Scientific Python SPEC0?
- [x] Add Python support policy to docs (e.g. in "User Guide > Policies"?)
- [ ] Update project dependencies to follow new policy
- [ ] #471
```

**Comment by Sherwin-14** [comment]
@mfisher87 Hey, Is this the policy that you are talking about https://jax.readthedocs.io/en/latest/deprecation.html. If yes then how should we implement this in our context?

**Comment by jhkennedy** [comment]
Numpy's Python version support policy is:
https://numpy.org/neps/nep-0029-deprecation_policy.html

Similarly, the scientific python policy is:
https://scientific-python.org/specs/spec-0000/

**Comment by mfisher87** [comment]
I think we're not decided yet on what policy we want to use. I personally think [Scientific Python SPEC0](https://scientific-python.org/specs/spec-0000/) (as referenced by your link above, and based on [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html)) is where we want to be.

> * Support for Python versions be dropped 3 years after their initial release.
> * Support for core package dependencies be dropped 2 years after their initial release. 

This means we can drop support for Python 3.9 now.

**Comment by mfisher87** [comment]
@'ing some folks I think may have opinions :) @betolink @andypbarrett @JessicaS11 @chuckwondo @asteiker @danielfromearth

**Comment by mfisher87** [comment]
I added a task list to the original post of this ticket. I think if whoever takes this up wants to break off the piece about updating our deps to another ticket, please do :)

**Comment by mfisher87** [comment]
Fairly positive emoji responses to request for consensus on SPEC0, maybe we can decide on the hackathon call rq. :)

**Comment by mfisher87** [comment]
I think we can call that complete :) I wonder about number 3, are our dependencies already in compliance or do we need to make changes?

**Comment by mfisher87** [comment]
This was completed https://earthaccess.readthedocs.io/en/latest/user_guide/backwards-compatibility/#our-python-and-dependency-support-policy

#763
